name:         Alex' Projects
description:  Open Source Flight Simulator Tools and more
url:          https://albar965.github.io/
theme:        jekyll-theme-tactile
repository:   albar965/albar965.github.io

gems:
  - jekyll-sitemap
